/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Venkat Suprabath
 */
public class MenuFormAdmin extends javax.swing.JFrame {

    /**
     * Creates new form MenuFormAdmin
     */
    public MenuFormAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BItemCheck = new javax.swing.JButton();
        BOrderPlace = new javax.swing.JButton();
        BAllOrders = new javax.swing.JButton();
        BSignOut = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BPending = new javax.swing.JButton();
        BProcessing = new javax.swing.JButton();
        BUtoA = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BItemCheck.setText("CHECK ITEMS");
        BItemCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BItemCheckActionPerformed(evt);
            }
        });

        BOrderPlace.setText("PLACE ORDER");
        BOrderPlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOrderPlaceActionPerformed(evt);
            }
        });

        BAllOrders.setText("ALL ORDERS");
        BAllOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAllOrdersActionPerformed(evt);
            }
        });

        BSignOut.setText("SIGN OUT");
        BSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSignOutActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("NILE");

        BPending.setText("CHECK PENDING ORDERS");

        BProcessing.setText("CHECK PROCESSING ORDERS");

        BUtoA.setText("ELEVATE USER TO ADMIN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(279, 279, 279))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(BItemCheck)
                                .addGap(18, 18, 18)
                                .addComponent(BOrderPlace))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(BAllOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(BSignOut)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BPending, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BProcessing, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BUtoA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(BPending)
                        .addGap(18, 18, 18)
                        .addComponent(BProcessing))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BItemCheck)
                            .addComponent(BOrderPlace))
                        .addGap(18, 18, 18)
                        .addComponent(BAllOrders)))
                .addGap(18, 18, 18)
                .addComponent(BUtoA)
                .addGap(28, 28, 28)
                .addComponent(BSignOut)
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BItemCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BItemCheckActionPerformed
        ItemsList frame = new ItemsList();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BItemCheckActionPerformed

    private void BOrderPlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOrderPlaceActionPerformed
        OrderPlace frame = new OrderPlace();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BOrderPlaceActionPerformed

    private void BAllOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAllOrdersActionPerformed
        AllOrders frame = new AllOrders();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BAllOrdersActionPerformed

    private void BSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSignOutActionPerformed
        LoginForm frame = new LoginForm();
        LoginForm.TFUserLogin.setText("");
        LoginForm.PFPassLogin.setText("");
        LoginForm.LUserStatus.setText("");
        this.setVisible(false);
        frame.setVisible(true);
    }//GEN-LAST:event_BSignOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuFormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuFormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuFormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuFormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuFormAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAllOrders;
    private javax.swing.JButton BItemCheck;
    private javax.swing.JButton BOrderPlace;
    private javax.swing.JButton BPending;
    private javax.swing.JButton BProcessing;
    private javax.swing.JButton BSignOut;
    private javax.swing.JButton BUtoA;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
